apiVersion: repo.crossplane.io/v1alpha1
kind: AutolinkReference
metadata:
  annotations:
    meta.upbound.io/example-id: repo/v1alpha1/autolinkreference
  labels:
    testing.upbound.io/example-name: autolink
  name: autolink
spec:
  forProvider:
    keyPrefix: TICKET-
    repositorySelector:
      matchLabels:
        testing.upbound.io/example-name: repo
    targetUrlTemplate: https://example.com/TICKET?query=<num>

---

apiVersion: repo.crossplane.io/v1alpha1
kind: Repository
metadata:
  annotations:
    meta.upbound.io/example-id: repo/v1alpha1/autolinkreference
  labels:
    testing.upbound.io/example-name: repo
  name: repo
spec:
  forProvider:
    description: GitHub repo managed by Terraform
    name: my-repo
    private: false
