apiVersion: repo.crossplane.io/v1alpha1
kind: BranchProtectionv3
metadata:
  annotations:
    meta.upbound.io/example-id: repo/v1alpha1/branchprotectionv3
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    branch: main
    repository: ${github_repository.example.name}
    restrictions:
    - users:
      - foo-user
