apiVersion: repo.crossplane.io/v1alpha1
kind: RepositoryWebhook
metadata:
  annotations:
    meta.upbound.io/example-id: repo/v1alpha1/repositorywebhook
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    pattern: v*
    repositorySelector:
      matchLabels:
        testing.upbound.io/example-name: example
