apiVersion: actions.crossplane.io/v1alpha1
kind: EnvironmentSecret
metadata:
  annotations:
    meta.upbound.io/example-id: actions/v1alpha1/environmentsecret
  labels:
    testing.upbound.io/example-name: example_secret
  name: example-secret
spec:
  forProvider:
    environment: example_environment
    plaintextValueSecretRef:
      key: example-key
      name: example-secret
      namespace: upbound-system
    secretName: example_secret_name
