apiVersion: actions.crossplane.io/v1alpha1
kind: Secret
metadata:
  annotations:
    meta.upbound.io/example-id: actions/v1alpha1/secret
  labels:
    testing.upbound.io/example-name: example_secret
  name: example-secret
spec:
  forProvider:
    plaintextValueSecretRef:
      key: example-key
      name: example-secret
      namespace: upbound-system
    repositorySelector:
      matchLabels:
        testing.upbound.io/example-name: example
    secretName: example_secret_name
